#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."
sed -i -E '/POT-Creation-Date:/d' i18n/contents+en.po i18n/contents+es.po i18n/contents+gl.po
msgattrib --sort-output --no-location --no-wrap i18n/contents+es.po --output i18n/contents+es.po
msgattrib --sort-output --no-location --no-wrap i18n/contents+gl.po --output i18n/contents+gl.po
msgattrib --sort-output --no-location --no-wrap i18n/contents+en.po --output i18n/contents+en.po
